# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f111b0aa3391df35141d25a334df2972357b74ac7e63b3289667587f94f8196aaef2b502806987312ec1edb2267e80c120b3c6b90f0dfd2287b9e99131cb45b

test:
  secret_key_base: 464657546742f1cd097031cdbf5220fb80ec6d6d11a6627ddc28368612c59b3e1cbc461d7db0d6bd8312b44013ffae63012168afc773d92b7ca107855f0af2f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
